### ISSUE TITLE
[Feature] - Builds fail when publishing to HCP Packer

### ISSUE THREAD

**Issue by tomasbasham** [vultr/packer-plugin-vultr#189] opened 2022-06-05 19:34 UTC
**Describe the bug**

When building an image and publishing build metadata to HCP Packer the post-processing stage fails and this in turn cleans up all the work done by the Vultr Packer plugin. Effectively the image build succeeds - I know this to be true as I am able to view all the assets in the Vultr dashboard, but when the post-processing stage kicks in the process fails with the following message:

```bash
Build 'vultr.almalinux' errored after 22 minutes 21 seconds: 1 error(s) occurred:

* Post-processor failed: [TRACE] failed to update Packer registry with image artifacts for "vultr.almalinux": setting a build to DONE with no published images is not currently supported.
```

This error only appears to happen with 3rd party plugins - plugins that were not created by HashiCorp - I suspect this because I am receiving the same error for another 3rd party Packer plugin for a different cloud provider, whilst all the HashiCorp providers run to completion.

**To Reproduce**

```terraform
packer {
  required_plugins {
    digitalocean = {
      version = ">= 1.0.4"
      source  = "github.com/hashicorp/digitalocean"
    }
    vultr = {
      version = ">= v2.4.4"
      source  = "github.com/vultr/vultr"
    }
}

build {
  hcp_packer_registry {
    bucket_name = "test-almalinux"
    description = "some description"

    bucket_labels = {
      "owner" = "platform-team"
    }

    build_labels = {
      "build-time"   = timestamp()
      "build-source" = basename(path.cwd)
    }
  }

  sources = [
    "source.digitalocean.almalinux",
    "source.vultr.almalinux",
  ]

  provisioner "shell" {
    inline = [
      "echo hello",
    ]
  }
}

source "vultr" "almalinux" {
  api_key              = "${var.api_key}"
  os_id                = "413"
  plan_id              = "vhf-1c-1gb"
  region_id            = "${var.upcloud_zone}"
  snapshot_description = "testing"
  state_timeout        = "10m"
  ssh_username         = "root"
}
```

**Expected behavior**

Metadata published to the HCP Packer application when builds succeed.

**Desktop (please complete the following information where applicable:**

 - OS: Ubunut
 - Packer Version 1.8.0
 - Vultr Version 2.4.4

This may possibly be a feature request rather than a bug.

**Comment by optik-aper** [comment] 2022-06-06 14:01
I am able to reproduce and will look into this.  Thanks for reporting it.

**Comment by optik-aper** [comment] 2022-06-06 16:23
It looks like we'll have to modify the plugin to match the required schema for the HCP registry.  [Documentation here](https://www.packer.io/docs/plugins/hcp-support).

**Comment by optik-aper** [comment] 2022-06-07 13:09
@tomasbasham We merged support for this into master if you want to give it a try.  It'll be in the next release if you'd rather wait for a binary.

**Comment by optik-aper** [comment] 2022-06-07 19:18
@tomasbasham Release [v2.4.5](https://github.com/vultr/packer-plugin-vultr/releases/tag/v2.4.5) adds support for the HCP registry if you want to check it out.

**Comment by tomasbasham** [comment] 2022-06-07 19:19
Magic, thank you. I'll check that out.

**Closed by optik-aper** 2022-06-07 19:18 UTC
Labels: enhancement
